### ISSUE TITLE
Please add checkbox to enable/disable sensors

### ISSUE THREAD

**Issue by pos-ei-don** [crycode-de/ioBroker.ds18b20#91]
Please add checkbox to enable/disable sensors.

I have some sensors that i only need in summer/winter (pool, etc.), so i'd like to be able to disable them without deleting them!
Or can i disable them by setting the interval to 0?

Thank you alot for this module!

**Comment by crycode-de** [comment]
You are able to disable the automatic sensor reading for each sensor by setting the interval to 0.
Nevertheless it will be read if you are using the `readNow` action state or the `read` action in scripts.

See also #89 

I'll add a checkbox to disable a sensor completely, but it may take some time due to other higher prio tasks atm.

**Comment by pos-ei-don** [comment]
Great THANK you! I did not find this  issue before, but writing 0 is totally good for me actually!!!

**Comment by Videonisse** [comment]
This is the same as #89 

It also solved the urgent issue for me, but maybe the Feature Request in #89 is still valid because the Adapter status is still yellow and it shows a red warning regarding the connection?

![image](https://user-images.githubusercontent.com/13684218/145442835-feeba56a-9e27-4025-b733-523d141c9439.png)

**Comment by crycode-de** [comment]
New option "enabled" is now available in v1.5.0 which can be installed via NPM know.
Tomorrow it will be in the latest repo and after some feedback I'll push it into stable.

Thank you for your report!

**Comment by Videonisse** [comment]
Many thanks, it works great!

**Comment by pos-ei-don** [comment]
Thank you a lot!
